const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs'); // Import bcrypt
const Pet = require('./models/Pet');
const User = require('./models/User');
const connectDB = require('./config/db');

dotenv.config();
connectDB();

const users = [
    {
        name: 'Admin User',
        email: 'qaisar@admin.com',
        password: '1112',
        isAdmin: true,
    },
    {
        name: 'John Doe',
        email: 'john@example.com',
        password: 'password123',
        isAdmin: false,
    },
    {
        name: 'Jane Smith',
        email: 'jane@example.com',
        password: 'password123',
        isAdmin: false,
    },
];

const pets = [
    {
        name: 'Buddy',
        type: 'Dog',
        breed: 'Golden Retriever',
        age: 3,
        description: 'Friendly and energetic golden retriever looking for an active family.',
        imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 250,
        likes: ['Belly rubs', 'Long walks', 'Peanut butter'],
        dislikes: ['Thunderstorms', 'Vacuum cleaners', 'Being alone'],
        games: ['Fetch', 'Tug of war', 'Hide and seek'],
        isAdopted: false,
    },
    {
        name: 'Luna',
        type: 'Cat',
        breed: 'Siamese',
        age: 2,
        description: 'Calm and affectionate Siamese cat.',
        imageUrl: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 150,
        likes: ['Warm laps', 'Window watching', 'Catnip'],
        dislikes: ['Loud noises', 'Water', 'Dogs chasing her'],
        games: ['Laser pointer', 'Feather wand', 'Box exploration'],
        isAdopted: false,
    },
    {
        name: 'Max',
        type: 'Dog',
        breed: 'German Shepherd',
        age: 4,
        description: 'Loyal and protective.',
        imageUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 300,
        likes: ['Training sessions', 'Car rides', 'Swimming'],
        dislikes: ['Mailmen', 'Squirrels', 'Baths'],
        games: ['Frisbee', 'Agility course', 'Find the treat'],
        isAdopted: false,
    },
    {
        name: 'Mittens',
        type: 'Cat',
        breed: 'Tabby',
        age: 1,
        description: 'Playful kitten.',
        imageUrl: 'https://images.unsplash.com/photo-1561948925-0bd72eb4c30c?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 100,
        likes: ['String', 'Climbing trees', 'Cuddling'],
        dislikes: ['Empty food bowl', 'Closed doors', 'Cucumbers'],
        games: ['Chasing tail', 'Pouncing', 'String chase'],
        isAdopted: false,
    },
    {
        name: 'Rocky',
        type: 'Dog',
        breed: 'Bulldog',
        age: 5,
        description: 'Stubborn but full of love.',
        imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 200,
        likes: ['Sleeping', 'Snoring', 'Gentle pats'],
        dislikes: ['Running', 'Hot weather', 'Stairs'],
        games: ['Nap time', 'Slow tug', 'Sitting contest'],
        isAdopted: false,
    },
    {
        name: 'Coco',
        type: 'Dog',
        breed: 'Poodle',
        age: 2,
        description: 'Smart and elegant.',
        imageUrl: 'https://images.unsplash.com/photo-1604542031653-57e0e1b9b073?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 400,
        likes: ['Grooming', 'Learning tricks', 'Soft pillows'],
        dislikes: ['Mud', 'Rain', 'Bad hair days'],
        games: ['High five', 'Dancing', 'Fetch'],
        isAdopted: false,
    },
    {
        name: 'Bella',
        type: 'Cat',
        breed: 'Persian',
        age: 3,
        description: 'Fluffy and regal.',
        imageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 500,
        likes: ['Brushing', 'Luxury treats', 'Quiet rooms'],
        dislikes: ['Knots in fur', 'Loud music', 'Unclean litter box'],
        games: ['Watching birds', 'Slow play', 'Sleeping'],
        isAdopted: false,
    },
    {
        name: 'Charlie',
        type: 'Dog',
        breed: 'Beagle',
        age: 1,
        description: 'Curious and energetic scent hound.',
        imageUrl: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 220,
        likes: ['Sniffing everything', 'Howling', 'Food'],
        dislikes: ['Being ignored', 'Baths', 'Citrus smells'],
        games: ['Scent work', 'Hide and seek', 'Running'],
        isAdopted: false,
    },
    {
        name: 'Simba',
        type: 'Cat',
        breed: 'Maine Coon',
        age: 4,
        description: 'Gentle giant of the cat world.',
        imageUrl: 'https://images.unsplash.com/photo-1557246565-d51c05d7b953?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 600,
        likes: ['Water', 'High places', 'Chirping at birds'],
        dislikes: ['Small spaces', 'Being carried', 'Strangers'],
        games: ['Water play', 'Climbing', 'Fetch'],
        isAdopted: false,
    },
    {
        name: 'Daisy',
        type: 'Dog',
        breed: 'Labrador Retriever',
        age: 2,
        description: 'Friendly and great with kids.',
        imageUrl: 'https://images.unsplash.com/photo-1591769225440-811ad7d6eca6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 280,
        likes: ['Swimming', 'Eating', 'Everyone she meets'],
        dislikes: ['Nothing really', 'Waiting for food', 'End of playtime'],
        games: ['Fetch', 'Swimming', 'Catch'],
        isAdopted: false,
    },
    {
        name: 'Nala',
        type: 'Cat',
        breed: 'Bengal',
        age: 1,
        description: 'Exotic look and very active.',
        imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 800,
        likes: ['Climbing high', 'Running wheels', 'Chatting'],
        dislikes: ['Boredom', 'Being held still', 'Closed doors'],
        games: ['Agility', 'Leash walking', 'Fetch'],
        isAdopted: false,
    },
    {
        name: 'Oscar',
        type: 'Dog',
        breed: 'Chihuahua',
        age: 2,
        description: 'Tiny but has a big personality.',
        imageUrl: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 180,
        likes: ['Warm blankets', 'Being carried', 'Barking at big dogs'],
        dislikes: ['Cold', 'Rain', 'Strangers'],
        games: ['Burrowing', 'Fetching mini toys', 'Cuddling'],
        isAdopted: false,
    },
    {
        name: 'Milo',
        type: 'Cat',
        breed: 'Ragdoll',
        age: 3,
        description: 'Blue-eyed and loves to be held.',
        imageUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 450,
        likes: ['Flopping', 'Being held like a baby', 'Soft food'],
        dislikes: ['Rough play', 'Heights', 'Solitude'],
        games: ['Gentle batting', 'Cuddle puddle', 'Following you'],
        isAdopted: false,
    },
    {
        name: 'Bear',
        type: 'Dog',
        breed: 'Newfoundland',
        age: 5,
        description: 'A massive, gentle, and loving dog.',
        imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 650,
        likes: ['Swimming', 'Children', 'Snow'],
        dislikes: ['Heat', 'Small spaces', 'Being rushed'],
        games: ['Water rescue', 'Pulling carts', 'Relaxing'],
        isAdopted: false,
    },
    {
        name: 'Duke',
        type: 'Dog',
        breed: 'Boxer',
        age: 3,
        description: 'Playful and muscular companion.',
        imageUrl: 'https://images.unsplash.com/photo-1555661330-90ac52eb9d50?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 350,
        likes: ['Jumping', 'Playing catch', 'Running in circles'],
        dislikes: ['Being alone', 'Extreme heat', 'Stillness'],
        games: ['Fetch', 'Tug', 'Agility'],
        isAdopted: false,
    },
    {
        name: 'Zoe',
        type: 'Dog',
        breed: 'Pug',
        age: 4,
        description: 'Charming and mischievous.',
        imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 300,
        likes: ['Snacks', 'Naps', 'Attention'],
        dislikes: ['Long runs', 'Hot days', 'Diets'],
        games: ['Snort contest', 'Sleep marathon', 'Cuddle'],
        isAdopted: false,
    },
    {
        name: 'Buster',
        type: 'Dog',
        breed: 'Dachshund',
        age: 2,
        description: 'Brave and independent long dog.',
        imageUrl: 'https://images.unsplash.com/photo-1612195583950-b8fd34c87093?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 250,
        likes: ['Digging', 'Burrowing in blankets', 'Barking'],
        dislikes: ['Stairs', 'Cold floors', 'Being scolded'],
        games: ['Tunnel run', 'Fetch', 'Digging'],
        isAdopted: false,
    },
    {
        name: 'Lola',
        type: 'Dog',
        breed: 'Cavalier King Charles Spaniel',
        age: 3,
        description: 'Affectionate and gentle lap dog.',
        imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 500,
        likes: ['Cuddling', 'Gentle walks', 'Belly rubs'],
        dislikes: ['Rough play', 'Loud noises', 'Being alone'],
        games: ['Fetch', 'Lap sitting', 'Gentle tug'],
        isAdopted: false,
    },
    {
        name: 'Leo',
        type: 'Cat',
        breed: 'British Shorthair',
        age: 5,
        description: 'Easygoing and dignified.',
        imageUrl: 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 400,
        likes: ['Lounging', 'Quiet observation', 'Good food'],
        dislikes: ['Being picked up', 'Loud music', 'Empty bowl'],
        games: ['Staring contest', 'Slow chase', 'Napping'],
        isAdopted: false,
    },
    {
        name: 'Cleo',
        type: 'Cat',
        breed: 'Sphynx',
        age: 2,
        description: 'Hairless and loves warmth.',
        imageUrl: 'https://images.unsplash.com/photo-1516045558957-c1d0e8ae19bf?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 900,
        likes: ['Sweaters', 'Sunbeams', 'Snuggling under covers'],
        dislikes: ['Cold drafts', 'Sunburn', 'Being ignored'],
        games: ['Warmth seeking', 'Shoulder riding', 'Fetch'],
        isAdopted: false,
    },
    {
        name: 'Jack',
        type: 'Dog',
        breed: 'Jack Russell Terrier',
        age: 2,
        description: 'High energy and intelligent.',
        imageUrl: 'https://images.unsplash.com/photo-1629831676369-1c9f807248c8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 200,
        likes: ['Jumping', 'Digging', 'Balls'],
        dislikes: ['Boredom', 'Being still', 'Leashes'],
        games: ['Fetch', 'Agility', 'Digging'],
        isAdopted: false,
    },
    {
        name: 'Sadie',
        type: 'Dog',
        breed: 'Border Collie',
        age: 3,
        description: 'Smartest dog you will ever meet.',
        imageUrl: 'https://images.unsplash.com/photo-1546975490-e8b92a360b24?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 350,
        likes: ['Working', 'Herding', 'Learning new tricks'],
        dislikes: ['Inactivity', 'Chaos', 'Thunder'],
        games: ['Frisbee', 'Obedience', 'Agility'],
        isAdopted: false,
    },
    {
        name: 'Oliver',
        type: 'Cat',
        breed: 'Scottish Fold',
        age: 2,
        description: 'Sweet natured with folded ears.',
        imageUrl: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 600,
        likes: ['Quiet', 'Gentle play', 'Food puzzles'],
        dislikes: ['Rough handling', 'Loud noises', 'Change'],
        games: ['Puzzle toys', 'Gentle fetch', 'Napping'],
        isAdopted: false,
    },
    {
        name: 'Lucy',
        type: 'Dog',
        breed: 'Shih Tzu',
        age: 6,
        description: 'Affectionate and happy house dog.',
        imageUrl: 'https://images.unsplash.com/photo-1579294246995-2ac744310d65?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 250,
        likes: ['Laps', 'Grooming', 'Short walks'],
        dislikes: ['Heat', 'Rough play', 'Stairs'],
        games: ['Lap warming', 'Fetch (short)', 'Snuggle'],
        isAdopted: false,
    },
    {
        name: 'Shadow',
        type: 'Cat',
        breed: 'Bombay',
        age: 3,
        description: 'Panther-like and friendly.',
        imageUrl: 'https://images.unsplash.com/photo-1549480017-d76466a4b7e8?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 300,
        likes: ['Following you', 'Warm spots', 'Play'],
        dislikes: ['Cold', 'Solitude', 'Loud noises'],
        games: ['Fetch', 'Stalking', 'Climbing'],
        isAdopted: false,
    },
    {
        name: 'Riley',
        type: 'Dog',
        breed: 'Australian Shepherd',
        age: 2,
        description: 'Versatile and energetic.',
        imageUrl: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 400,
        likes: ['Running', 'Herding', 'Frisbee'],
        dislikes: ['Boredom', 'Confinement', 'Inactive days'],
        games: ['Frisbee', 'Agility', 'Herding'],
        isAdopted: false,
    },
    {
        name: 'Ruby',
        type: 'Dog',
        breed: 'Corgi',
        age: 1,
        description: 'Short legs, big personality.',
        imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 550,
        likes: ['Herding heels', 'Food', 'Belly rubs'],
        dislikes: ['Stairs', 'Being ignored', 'Empty bowel'],
        games: ['Chase', 'Tug', 'Puzzle toys'],
        isAdopted: false,
    },
    {
        name: 'Willow',
        type: 'Cat',
        breed: 'Russian Blue',
        age: 4,
        description: 'Quiet and gentle.',
        imageUrl: 'https://images.unsplash.com/photo-1511044568932-338cba0fb803?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 500,
        likes: ['Quiet environments', 'Loyalty', 'Routine'],
        dislikes: ['Strangers', 'Chaos', 'Change'],
        games: ['Feather wand', 'Cuddling', 'Watching'],
        isAdopted: false,
    },
    {
        name: 'Penny',
        type: 'Dog',
        breed: 'Cocker Spaniel',
        age: 3,
        description: 'Happy and gentle.',
        imageUrl: 'https://images.unsplash.com/photo-1563223697-b673ab489a56?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 280,
        likes: ['Sniffing', 'Cuddles', 'Treats'],
        dislikes: ['Loud noises', 'Rough handling', 'Being alone'],
        games: ['Fetch', 'Scent work', 'Cuddle'],
        isAdopted: false,
    },
    {
        name: 'Jasper',
        type: 'Cat',
        breed: 'Abyssinian',
        age: 2,
        description: 'Active and curious.',
        imageUrl: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
        price: 600,
        likes: ['Climbing', 'Exploring', 'Playing fetch'],
        dislikes: ['Sitting still', 'Boredom', 'Being held too long'],
        games: ['Fetch', 'Climbing', 'Puzzle toys'],
        isAdopted: false,
    },
];

const importData = async () => {
    try {
        await User.deleteMany(); // Clear users
        await Pet.deleteMany(); // Clear pets

        // Hash passwords
        const salt = await bcrypt.genSalt(10);
        const adminHashedPassword = await bcrypt.hash('1112', salt);
        const userHashedPassword = await bcrypt.hash('password123', salt);

        const usersWithHashedPasswords = users.map(user => ({
            ...user,
            password: user.isAdmin ? adminHashedPassword : userHashedPassword
        }));

        const createdUsers = await User.insertMany(usersWithHashedPasswords);

        await Pet.insertMany(pets);

        console.log('Data Imported with hashed passwords!');
        process.exit();
    } catch (error) {
        console.error(`${error}`);
        process.exit(1);
    }
};

importData();
